AWSTemplateFormatVersion: '2010-09-09'
Description: PR Preview Environment (EC2 + RDS from snapshot)

Parameters:

  PRNumber:
    Type: String
    Description: Pull Request Number

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

  AMI:
    Type: AWS::EC2::Image::Id

  InstanceType:
    Type: String
    Default: t3.micro

  SubnetId:
    Type: AWS::EC2::Subnet::Id

  SecurityGroupId:
    Type: String
    Description: Security group allowing EC2 and RDS access

  DBSnapshotIdentifier:
    Type: String
    Description: RDS snapshot identifier

  DBUsername:
    Type: String
    Default: admin

  DBPassword:
    Type: String
    NoEcho: true

  DBSubnetGroup:
    Type: String
    Description: Existing RDS Subnet Group

Resources:

  # ------------------------------------------
  # RDS Instance from snapshot
  # ------------------------------------------
  PreviewRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub pr-preview-db-${PRNumber}
      DBSnapshotIdentifier: !Ref DBSnapshotIdentifier
      DBInstanceClass: db.t3.micro
      Engine: mysql
      PubliclyAccessible: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref SecurityGroupId
      DeletionProtection: false
      DeleteAutomatedBackups: true
      Tags:
        - Key: PR
          Value: !Ref PRNumber

  # ------------------------------------------
  # EC2 Instance
  # ------------------------------------------
  PreviewEC2:
    Type: AWS::EC2::Instance
    DependsOn: PreviewRDS
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMI
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub pr-preview-${PRNumber}
        - Key: PR
          Value: !Ref PRNumber
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          APP_DIR="/var/www/cicd"
          REPO="https://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@github.com/sanjayjangir1093/cicd.git"
          VENV_DIR="$APP_DIR/venv"
          SOCKET="$APP_DIR/gunicorn.sock"
          USER="ubuntu"
          GROUP="www-data"
          DJANGO_APP="todoApp"

          DB_HOST=${PreviewRDS.Endpoint.Address}
          DB_NAME=temp
          DB_USER=${DBUsername}
          DB_PASSWORD=${DBPassword}
          DB_PORT=3306

          apt-get update -y
          apt-get upgrade -y
          apt-get install -y python3-pip python3-venv python3-dev build-essential git nginx mysql-client

          rm -rf $APP_DIR
          git clone $REPO $APP_DIR
          cd $APP_DIR

          chown -R $USER:$GROUP $APP_DIR
          chmod -R 775 $APP_DIR

          python3 -m venv venv
          source $VENV_DIR/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

          export DJANGO_DB_HOST=$DB_HOST
          export DJANGO_DB_NAME=$DB_NAME
          export DJANGO_DB_USER=$DB_USER
          export DJANGO_DB_PASSWORD=$DB_PASSWORD
          export DJANGO_DB_PORT=$DB_PORT

          python manage.py migrate
          python manage.py collectstatic --noinput
          deactivate

          cat > /etc/systemd/system/gunicorn.service << EOF
          [Unit]
          Description=Gunicorn daemon for PR Preview
          After=network.target

          [Service]
          User=$USER
          Group=$GROUP
          WorkingDirectory=$APP_DIR
          Environment="PATH=$VENV_DIR/bin:\$PATH"
          ExecStart=$VENV_DIR/bin/gunicorn --workers 3 --bind unix:$SOCKET $DJANGO_APP.wsgi:application
          Restart=always
          RestartSec=3

          [Install]
          WantedBy=multi-user.target
          EOF

          systemctl daemon-reload
          systemctl enable gunicorn
          systemctl restart gunicorn

          cat > /etc/nginx/sites-available/cicd << EOF
          server {
              listen 80;
              server_name _;

              location /static/ {
                  alias $APP_DIR/static/;
              }

              location / {
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_pass http://unix:$SOCKET;
              }

              access_log /var/log/nginx/cicd-access.log;
              error_log /var/log/nginx/cicd-error.log;
          }
          EOF

          ln -sf /etc/nginx/sites-available/cicd /etc/nginx/sites-enabled/
          rm -f /etc/nginx/sites-enabled/default
          nginx -t
          systemctl restart nginx

Outputs:

  PreviewEC2IP:
    Description: EC2 Public IP
    Value: !GetAtt PreviewEC2.PublicIp

  PreviewURL:
    Description: Application URL
    Value: !Sub http://${PreviewEC2.PublicIp}

  RDSEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt PreviewRDS.Endpoint.Address
