AWSTemplateFormatVersion: "2010-09-09"
Description: PR Preview - EC2 + RDS + Django Deployment

Parameters:
  PRNumber:
    Type: String
  KeyName:
    Type: String
  AMI:
    Type: String
  SubnetId:
    Type: String
  SecurityGroupId:
    Type: String
  DBSnapshotIdentifier:
    Type: String
  DBSubnetGroup:
    Type: String
  DBUsername:
    Type: String
    Default: admin
  DBPassword:
    Type: String
    NoEcho: true
  GitHubToken:
    Type: String
    NoEcho: true
  RepoURL:
    Type: String

Resources:

  PRPreviewDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "pr-preview-db-${PRNumber}"
      DBSnapshotIdentifier: !Ref DBSnapshotIdentifier
      DBInstanceClass: db.t3.micro
      Engine: mysql
      PubliclyAccessible: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref SecurityGroupId

  PRPreviewEC2:
    Type: AWS::EC2::Instance
    DependsOn: PRPreviewDB
    Properties:
      ImageId: !Ref AMI
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub "pr-preview-${PRNumber}"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          APP_DIR="/var/www/cicd"
          VENV_DIR="$APP_DIR/venv"
          SOCKET="$APP_DIR/gunicorn.sock"
          USER="ubuntu"
          GROUP="www-data"
          DJANGO_APP="todoApp"

          DB_HOST="${PRPreviewDB.Endpoint.Address}"
          DB_NAME="temp"
          DB_USER="${DBUsername}"
          DB_PASSWORD="${DBPassword}"
          DB_PORT=3306

          # Install dependencies
          apt-get update -y
          apt-get install -y netcat git python3-pip python3-venv python3-dev build-essential nginx mysql-client

          # Wait for DB
          until nc -z -v -w30 $DB_HOST 3306
          do
            echo "Waiting for DB..."
            sleep 10
          done

          # Clone repo securely
          git clone https://${GitHubToken}@github.com/sanjayjangir1093/cicd.git $APP_DIR
          cd $APP_DIR

          chown -R $USER:$GROUP $APP_DIR
          chmod -R 775 $APP_DIR

          python3 -m venv venv
          source $VENV_DIR/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

          export DJANGO_DB_HOST=$DB_HOST
          export DJANGO_DB_NAME=$DB_NAME
          export DJANGO_DB_USER=$DB_USER
          export DJANGO_DB_PASSWORD=$DB_PASSWORD
          export DJANGO_DB_PORT=$DB_PORT

          python manage.py migrate
          python manage.py collectstatic --noinput
          deactivate

          # Gunicorn service
          cat >/etc/systemd/system/gunicorn.service <<'EOF'
[Unit]
Description=Gunicorn
After=network.target

[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/var/www/cicd
Environment="PATH=/var/www/cicd/venv/bin:$PATH"
ExecStart=/var/www/cicd/venv/bin/gunicorn --workers 3 --bind unix:/var/www/cicd/gunicorn.sock todoApp.wsgi:application
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

          systemctl daemon-reload
          systemctl enable gunicorn
          systemctl restart gunicorn

          # Nginx config
          cat >/etc/nginx/sites-available/cicd <<'EOF'
server {
    listen 80;
    server_name _;
    location /static/ {
        alias /var/www/cicd/static/;
    }
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://unix:/var/www/cicd/gunicorn.sock;
    }
}
EOF

          ln -sf /etc/nginx/sites-available/cicd /etc/nginx/sites-enabled/
          rm -f /etc/nginx/sites-enabled/default
          nginx -t
          systemctl restart nginx

Outputs:
  AppURL:
    Description: Preview URL
    Value: !Sub "http://${PRPreviewEC2.PublicIp}"
